//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.08 at 11:10:41 AM EST 
//


package gov.raleigh.employeeservice.service.impl;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}registerId"/>
 *         &lt;element ref="{}readSequence"/>
 *         &lt;element ref="{}readType"/>
 *         &lt;element ref="{}dials"/>
 *         &lt;element ref="{}mrSource"/>
 *         &lt;element ref="{}lowMeterReadingWarning"/>
 *         &lt;element ref="{}highMeterReadingWarning"/>
 *         &lt;element ref="{}lastMeterRead"/>
 *         &lt;element ref="{}MIU"/>
 *         &lt;element ref="{}RegisterSize"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "registerId",
    "readSequence",
    "readType",
    "dials",
    "mrSource",
    "lowMeterReadingWarning",
    "highMeterReadingWarning",
    "lastMeterRead",
    "miu",
    "registerSize"
})
@XmlRootElement(name = "Registers")
public class Registers {

    @XmlElement(required = true)
    protected BigInteger registerId;
    @XmlElement(required = true)
    protected BigInteger readSequence;
    @XmlElement(required = true)
    protected BigInteger readType;
    @XmlElement(required = true)
    protected BigInteger dials;
    @XmlElement(required = true)
    protected String mrSource;
    @XmlElement(required = true)
    protected BigDecimal lowMeterReadingWarning;
    @XmlElement(required = true)
    protected BigDecimal highMeterReadingWarning;
    @XmlElement(required = true)
    protected BigDecimal lastMeterRead;
    @XmlElement(name = "MIU", required = true)
    protected BigInteger miu;
    @XmlElement(name = "RegisterSize", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String registerSize;

    /**
     * Gets the value of the registerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRegisterId() {
        return registerId;
    }

    /**
     * Sets the value of the registerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRegisterId(BigInteger value) {
        this.registerId = value;
    }

    /**
     * Gets the value of the readSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReadSequence() {
        return readSequence;
    }

    /**
     * Sets the value of the readSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReadSequence(BigInteger value) {
        this.readSequence = value;
    }

    /**
     * Gets the value of the readType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReadType() {
        return readType;
    }

    /**
     * Sets the value of the readType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReadType(BigInteger value) {
        this.readType = value;
    }

    /**
     * Gets the value of the dials property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDials() {
        return dials;
    }

    /**
     * Sets the value of the dials property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDials(BigInteger value) {
        this.dials = value;
    }

    /**
     * Gets the value of the mrSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrSource() {
        return mrSource;
    }

    /**
     * Sets the value of the mrSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrSource(String value) {
        this.mrSource = value;
    }

    /**
     * Gets the value of the lowMeterReadingWarning property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLowMeterReadingWarning() {
        return lowMeterReadingWarning;
    }

    /**
     * Sets the value of the lowMeterReadingWarning property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLowMeterReadingWarning(BigDecimal value) {
        this.lowMeterReadingWarning = value;
    }

    /**
     * Gets the value of the highMeterReadingWarning property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHighMeterReadingWarning() {
        return highMeterReadingWarning;
    }

    /**
     * Sets the value of the highMeterReadingWarning property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHighMeterReadingWarning(BigDecimal value) {
        this.highMeterReadingWarning = value;
    }

    /**
     * Gets the value of the lastMeterRead property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLastMeterRead() {
        return lastMeterRead;
    }

    /**
     * Sets the value of the lastMeterRead property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLastMeterRead(BigDecimal value) {
        this.lastMeterRead = value;
    }

    /**
     * Gets the value of the miu property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMIU() {
        return miu;
    }

    /**
     * Sets the value of the miu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMIU(BigInteger value) {
        this.miu = value;
    }

    /**
     * Gets the value of the registerSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterSize() {
        return registerSize;
    }

    /**
     * Sets the value of the registerSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterSize(String value) {
        this.registerSize = value;
    }

}
